version: '3.4'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    # expose:
    #   - 27017
    ports:
      # - "127.0.0.1:27017:27017"
      # - "27017:27017/udp"
      # - "27017:27017/tcp"
      - 27017:27017
      # - "27017"
    # volumes:
    #   - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_DATABASE: deno-db
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      MONGO_INITDB_ROOT_USERNAME: docker

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-web-admin
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: docker
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopw
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: "0.0.0.0"
      # ME_CONFIG_MONGODB_SERVER: 0.0.0.0
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_URL: mongodb://docker:mongopw@mongo:27017/
      # ME_CONFIG_MONGODB_URL: mongodb://docker:mongopw@0.0.0.0:27017/
      # ME_CONFIG_MONGODB_URL: mongodb://docker:mongopw@0.0.0.0:27017

  webapp:
    # image: denoplayground
    container_name: webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      WAIT_HOSTS: mongodb:27017
    env_file: .env
    depends_on:
      - mongo

# volumes:
#   mongodb_data_container
