# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno Test and Publish

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        # uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --allow-env --config ./deno.jsonc --jobs --coverage=./coverage ./test

      - name: Generate test coverage
        run: deno coverage ./coverage --lcov > ./coverage/lcov.info

      - name: Code Coverage Report (as artifact)
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage

  deploy:
    # more info - https://github.com/denoland/deployctl/blob/main/action/README.md
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Create dist directory
        run: mkdir ./dist

      - name: Create Single JS File in dist directory
        run: deno bundle ./src/index.ts ./dist/index.js

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fast-rabbit-27 # the name of the project on Deno Deploy
          # entrypoint: ./src/index.ts # the entrypoint to deploy relative to `root`
          # entrypoint: ../src/index.ts  'file:///home/runner/work/deno-playground/src/index.ts'
          # entrypoint: src/index.ts     'file:///src/src/index.ts'
          # entrypoint: ./index.ts       'file:///src/index.ts'
          # entrypoint: /index.ts        'file:///index.ts'
          # entrypoint: file://index.ts  'file://index.ts/'
          # entrypoint: file:///index.ts 'file:///index.ts'
          # entrypoint: index.ts
          # entrypoint: file:///src/index.ts
          # entrypoint: file://src/index.ts
          # root: ./src/
          # root: src
          # root: ./src
          # entrypoint: index.ts
          # root: src
          entrypoint: index.js
          root: dist
