# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno Test and Publish

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        # uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --allow-env --config ./deno.jsonc --jobs --coverage=./coverage ./test

      - name: Generate test coverage
        run: deno coverage ./coverage --lcov > ./coverage/lcov.info

      - name: Code Coverage Report (as artifact)
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage

  deploy:
    # more info - https://github.com/denoland/deployctl/blob/main/action/README.md
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - name: Create dist directory
        ### attempt 1 (works)
        # run: mkdir ./dist
        ### attempt 2
        # run: mkdir /dist
        ### attempt 3
        # run: mkdir /tmp/dist

      # - name: Create Single JS File in dist directory
        # run: deno bundle --reload ./index.ts ./dist/index.js
        # run: deno bundle --reload ./index.ts /dist/index.js
        # run: deno bundle --reload ./index.ts dist/index.js
        # run: deno bundle --reload ./index.ts /tmp/dist/index.js

      - name: Create Single JS File (/tmp/index.js)
        run: deno bundle --reload ./index.ts /tmp/index.js

      - name: Copy JS File (./src/index.js)
        run: cp /tmp/index.js ./src/index.js

      - name: Copy JS File (./index.js)
        run: cp /tmp/index.js ./index.js


      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fast-rabbit-27 # the name of the project on Deno Deploy
          # entrypoint: ./src/index.ts # the entrypoint to deploy relative to `root`
          # entrypoint: ../src/index.ts  'file:///home/runner/work/deno-playground/src/index.ts'
          # entrypoint: src/index.ts     'file:///src/src/index.ts'
          # entrypoint: ./index.ts       'file:///src/index.ts'
          # entrypoint: /index.ts        'file:///index.ts'
          # entrypoint: file://index.ts  'file://index.ts/'
          # entrypoint: file:///index.ts 'file:///index.ts'
          # entrypoint: index.ts
          # entrypoint: file:///src/index.ts
          # entrypoint: file://src/index.ts
          # root: ./src/
          # root: src
          # root: ./src
          # entrypoint: index.ts
          # root: src
          ### attempt 1
          # entrypoint: index.js
          # root: dist
          ### attempt 2
          # entrypoint: ./dist/index.js
          ### attempt 3
          # entrypoint: index.js
          ### attempt 4
          # entrypoint: dist/index.js
          ### attempt 5
          # entrypoint: file:///dist/index.js
          ### attempt 6 - use known writable dir
          # entrypoint: file:///tmp/dist/index.js
          ### attempt 7
          # entrypoint: index.js
          # root: file:///tmp/dist
          ### attempt 8
          # entrypoint: index.js
          # root: /tmp/dist
          ### attempt 9
          # entrypoint: ./index.js
          # root: /tmp/dist
          ### attempt 10
          # entrypoint: file:///tmp/dist/index.js
          # root: /tmp/dist
          ### attempt 11
          # entrypoint: file:///tmp/dist/index.js
          # root: file:///tmp/dist
          ### attempt 12 - Failed to open entrypoint file at 'file:///home/runner/work/deno-playground/deno-playground/file:/tmp/index.js': ENOENT: no such file or directory, lstat '/home/runner/work/deno-playground/deno-playground/file:/tmp/index.js'
          # entrypoint: index.js
          # root: file:///tmp
          ### attempt 13 - Failed to open entrypoint file at 'file:///home/runner/work/deno-playground/deno-playground/file:/tmp/index.js': ENOENT: no such file or directory, lstat '/home/runner/work/deno-playground/deno-playground/file:/tmp/index.js'
          # entrypoint: index.js
          # root: file://tmp
          ### attempt 14 - Error: EACCES: permission denied, opendir '/tmp/systemd-private-99407c63964a41ec8c66ae9be7f1049b-ModemManager.service-3oh7th'
          # entrypoint: index.js
          # root: /tmp
          ### attempt 15 - Uploading 1 file(s) (total 5049 bytes)
          # entrypoint: index.js
          ### attempt 16 - Uploading 1 file(s) (total 5150 bytes)
          # entrypoint: ./index.js
          ### attempt 17 - Entrypoint must be in the working directory (cwd, or specified root directory).
          # entrypoint: file:///tmp/index.js
          ### attempt 18 - Entrypoint must be in the working directory (cwd, or specified root directory).
          # entrypoint: file:///tmp/index.js
          # root: file:///tmp
          ### attempt 19 - Failed to open entrypoint file at 'file:///home/runner/work/deno-playground/deno-playground/file:/tmp/index.js': ENOENT: no such file or directory, lstat '/home/runner/work/deno-playground/deno-playground/file:/tmp/index.js'
          entrypoint: ./index.js
          root: file:///tmp
          ### attempt 20
          entrypoint: file:///index.js
          root: file:///tmp
